server:
  port: 8095

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.30:3306/datasource
    username: root
    password: roow
  #redis连接池信息
  redis:
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
    timeout: 20000  # 连接超时时间（毫秒）
    database: 0  # Redis数据库索引（默认为0）
    #配置哨兵集群
    sentinel:
      master: mymaster
      nodes: 192.168.15.128:26379,192.168.15.128:26380,192.168.15.128:26381
    cluster:
      #配置redis集群
      nodes: 192.168.15.128:6379,192.168.15.128:6380,192.168.15.128:6381

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl