server:
  port: 8096

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.30:3306/datasource
    username: root
    password: roow
  data:
    mongodb:
      host: 192.168.1.30
      port: 27017
      database: test

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl